// importar o app para o server
const app = require("./src/app")
// aqui eu tenho que criar uma porta como uma variavel
const PORT = 7070
// utilizar o app.listen, para ouvir a porta.
app.listen(PORT, () => {
    console.log(`Você consegue! A porta ${PORT} está funcionando.`)
})



/* OLÁ PROFESSORA, TO FELIZ E CANSADA AO MESMO TEMPO. 
FIZ SOZINHA ESSA ATIVIDADE, REVENDO A SUA AULA, POIS NÃO LEMBRO DE TUDO E AINDA TENHO ALGUMAS DPUVIDAS.
MAS, FAZENDO A ATIVIDADE PERCEBI QUE MEHLHOREI MUITO E SINTO UMA LEVE CONFIANÇA, SO DEUS SABE COMO TEM 
SIDO CORRIDO PRA MIM DAR CONTA DA FACULDADE, SEMANA DE PROVA E O REPROGRAMA, GOSTO MUITO DAS SUAS AULAS,
POIS, NELAS EU CONSIGO ACOMPANHAR. NÃO QUE AS OUTRAS PROFESSORAS FORAM RUINS, O PROBLEMA É QUE O MEU RITMO
DE APRENDIZAGEM É LENTO. 
NA ATIVIDADE PARA O LAR EU FIZ UMA API DE MATRICULA, COMO ESTOU EM SEMANA DE PROVA DA FACULDADE E REFAZENDO 
A MATRICULA PARA O PROXIMO PERÍODO, ISSO NÃO SAIU DA MINHA CABEÇA E DECIDI COLOCAR EM PRATICA. ESPERO QUE ESTEJA
TUDO CERTO, DA MANEIRA QUE A SENHORA PEDIU, BEIJO GRANDE, QUE DEUS LHE ABENÇÕE. */
